### ISSUE TITLE
How to reproduce transfer learning result on Table 4?

### ISSUE THREAD

**Issue by yxchng** [facebookresearch/asym-siam#5]
<img width="953" alt="Screenshot 2022-05-01 at 5 21 54 PM" src="https://user-images.githubusercontent.com/10518587/166140044-3de321ee-f492-4ac5-9d7e-488a9dc2cb7d.png">

Hi, how can I reproduce the results in this table? Is there any open source code that you use? If not, do you mind releasing them?

**Comment by endernewton** [comment]
Thanks for the interest in our work! There is no plan for releasing this part of the code. If you are interested, just use the hyper-parameter search protocol we described in the paper, and given the similarity to the linear-eval protocol of IN, it should not be too difficulty to reproduce the results.

**Comment by yxchng** [comment]
@endernewton It is not easy to reproduce the result in your paper. You can refer to the conversation here https://github.com/linusericsson/ssl-transfer/issues/8. Papers are published using different setups and details in different papers and numbers can vary significantly!

**Comment by endernewton** [comment]
Have you tried specifically for our paper? I think at one point we are indeed discussing about releasing the code as a contribution to this (I know it is a bit messy there, especially for results inside/outside of Google -- just a different eco-system for training etc). However, I think our setup is closer to the external code ones released in PyTorch, and Google ones may have different setups due to TF/TPU etc.

**Comment by haooooooqi** [comment]
Hi @yxchng,
Thanks so much for interested in our paper!
Currently we don't have an immediate plan to release the downstream training code, as it's an important but orthogonal direction to our method in the paper. 
Due to other high priority open source/ research project plans, we currently can not get enough resource to prioritize the downstream code refactor, releasing and the following maintenance (I can imagine it is nontrivial). 
We will let you know immediately once we could possibly prioritize it.
Thanks so much :)
